pincher_x100_controller:
  ros__parameters:
    use_platform: true
    control_period: 0.010
    # use_moveit: false
    use_moveit: false
    # planning_group_name: "arm"
    # moveit_sample_duration: 0.050
