#!/bin/bash

echo ""
echo "This script copies a udev rule to /etc to facilitate bringing"
echo "up the Trossen's Pincher Arm usb connection."
echo ""

# sudo cp `rospack find pincher_x100_controller`/99-pincher-cdc.rules /etc/udev/rules.d/
sudo cp `ros2 pkg prefix pincher_x100_controller`/share/pincher_x100_controller/99-pincher-cdc.rules /etc/udev/rules.d/

echo ""
echo "Reload rules"
echo ""
sudo udevadm control --reload-rules
sudo udevadm trigger

# sudo chmod a+rw /dev/ttyUSB0
